### PR TITLE
Seller

### PR DESCRIPTION
**Pull request by for2ver0**
으아아아

### CODE REVIEW

**Comment by 34-43** [comment]
.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*
.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*

**Comment by 34-43** [comment]
.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*

**Review by 34-43 — APPROVED** [review]
.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*#.,.#*`*

**Review by Despereaux-MAU — APPROVED** [review]
LGTM

**Pull request merged**
